In [1]:
import sys
import numpy as np

In [2]:
np.array([1, 2, 3, 4])


array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([5.0, 6, 7.4, 8])
a[0], a[1]

(1, 2)

In [6]:
a[2:]

array([3, 4])

In [7]:
a[-1]

4

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])


a[::2] is a Python expression that refers to every second element of the list a. The double colons (::) indicate that the start and stop indices are omitted, so the entire list is used. The step size is 2, so the expression will return the elements at indices 0, 2, 4, and so on.



In [10]:
b

array([5. , 6. , 7.4, 8. ])

In [11]:
b[0], b[1], b[-1]

(5.0, 6.0, 8.0)

In [12]:
b[[0, 2, -1]]

array([5. , 7.4, 8. ])

b[[-2::-1]] returns a new list containing the last two elements of the list b, in reverse order.

In [16]:
b[-2::-1]

array([7.4, 6. , 5. ])

ARRAYS AND TYPES

In [17]:
a

array([1, 2, 3, 4])

In [18]:
a.dtype

dtype('int64')

In [19]:
b

array([5. , 6. , 7.4, 8. ])

In [20]:
b.dtype

dtype('float64')

In [21]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [23]:
np.array([1, 2, 3, 4], dtype=np.int64)

array([1, 2, 3, 4])

In [25]:
c = np.array(['a', 'b', 'c'])
c.dtype

dtype('<U1')

In [28]:
d = np.array([{'a': 1}, sys])
d.dtype

dtype('O')

DIMENSIONS AND SHAPES

In [38]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
])
a.shape

(2, 3)


A dimension in NumPy is a way of organizing data into a hierarchy. For example, a one-dimensional array is a list of numbers, a two-dimensional array is a list of lists of numbers, and a three-dimensional array is a list of lists of lists of numbers.

The number of dimensions of an array is also known as its rank. A one-dimensional array has rank 1, a two-dimensional array has rank 2, and a three-dimensional array has rank 3.

In [39]:
a.ndim

2

In [40]:
a.size

6

In [41]:
b = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [42]:
b.ndim

3

In [44]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])
C.dtype

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

INDEXING AND SLICING OF MATRICES

In [45]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [46]:
a[1]

array([4, 5, 6])

In [47]:
a[1 ,0]

4

In [48]:
a[0:2]


array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
a[:, :2] #all rows included, but just the first two elements in the dimension 

array([[1, 2],
       [4, 5],
       [7, 8]])

In [50]:
a[:2, :2]

array([[1, 2],
       [4, 5]])

In [51]:
a[:2, 2:]

array([[3],
       [6]])

In [54]:
a[1] = np.array([10, 10, 10])
a

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [57]:
a[1] = 99
a


array([[ 1,  2,  3],
       [99, 99, 99],
       [ 7,  8,  9]])

SUMMARY STATISTICS

In [58]:
a = np.array([1, 2, 3, 4, 5])

In [59]:
a.sum()

15

In [60]:
a.mean()

3.0

In [61]:
a.sort()

In [62]:
a.std()

1.4142135623730951

In [64]:
a.var() #to calculate the variance

2.0

In [65]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [66]:
a.sum(axis=0)

array([12, 15, 18])

In [67]:
a.sum(axis=1)

array([ 6, 15, 24])

In [68]:
a.mean(axis=0)

array([4., 5., 6.])

In [69]:
a.mean(axis=1)

array([2., 5., 8.])

In [70]:
a.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [71]:
a.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

BROADCASTING AND VECTORIZATION OPERATIONS


The NumPy code a = np.arange(4) creates a one-dimensional NumPy array containing the integers 0, 1, 2, and 3.

The np.arange() function is used to generate an array of evenly spaced values within a given interval. The interval is defined by the start, stop, and step arguments. The start argument is the first value in the array, the stop argument is the last value in the array (but not including the stop value), and the step argument is the spacing between the values in the array.

In the code a = np.arange(4), the start argument is not specified, so it defaults to 0. The stop argument is 4, and the step argument is not specified, so it defaults to 1. This means that the array a will contain the integers 0, 1, 2, and 3.



In [72]:
a = np.arange(4)

In [73]:
a

array([0, 1, 2, 3])

In [74]:
a + 10

array([10, 11, 12, 13])

In [76]:
a += 100
a

array([200, 201, 202, 203])