In [1]:
import sys
import numpy as np

In [2]:
np.array([1, 2, 3, 4])


array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([5.0, 6, 7.4, 8])
a[0], a[1]

(1, 2)

In [6]:
a[2:]

array([3, 4])

In [7]:
a[-1]

4

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])


a[::2] is a Python expression that refers to every second element of the list a. The double colons (::) indicate that the start and stop indices are omitted, so the entire list is used. The step size is 2, so the expression will return the elements at indices 0, 2, 4, and so on.



In [10]:
b

array([5. , 6. , 7.4, 8. ])

In [11]:
b[0], b[1], b[-1]

(5.0, 6.0, 8.0)

In [12]:
b[[0, 2, -1]]

array([5. , 7.4, 8. ])

b[[-2::-1]] returns a new list containing the last two elements of the list b, in reverse order.

In [16]:
b[-2::-1]

array([7.4, 6. , 5. ])

ARRAYS AND TYPES

In [17]:
a

array([1, 2, 3, 4])

In [18]:
a.dtype

dtype('int64')

In [19]:
b

array([5. , 6. , 7.4, 8. ])

In [20]:
b.dtype

dtype('float64')

In [21]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [23]:
np.array([1, 2, 3, 4], dtype=np.int64)

array([1, 2, 3, 4])

In [25]:
c = np.array(['a', 'b', 'c'])
c.dtype

dtype('<U1')

In [28]:
d = np.array([{'a': 1}, sys])
d.dtype

dtype('O')

DIMENSIONS AND SHAPES